# required metadata
sonar.projectKey=bank-ledger
sonar.projectName=bank-ledger
sonar.projectVersion=1.0

# optional description
sonar.projectDescription=Scan project.

# path to source directories (required)
sonar.sources=src/main/java
sonar.java.source=17

# path to test source directories (optional)
sonar.tests=src/test/java

# path to project binaries (optional), for example directory of Java bytecode
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

# optional comma-separated list of paths to libraries. Only path to JAR file is supported.
#sonar.libraries=lib/*.jar
# The value of the property must be the key of the language.
sonar.language=java

# Coverage report path
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Additional parameters

# setting sonar credentials through generated token
sonar.login=squ_ad474099062a816868aa69e52ef8d0b90725f599

# setting the port of sonarqube
# sonar.host.url=<port where sonarqube is running>
# ex:
sonar.host.url=http://localhost:9000

#prevent scm error
sonar.scm.disabled=true
